# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: react-frontend
# # spec:
# #   selector:
# #     app: react-frontend
# #   ports:
# #   - protocol: TCP
# #     port: 80
# #     targetPort: 80
# #   type: LoadBalancer

# apiVersion: v1
# kind: Service
# metadata:
#   name: react-frontend
# spec:
#   selector:
#     app: react-frontend
#   type: LoadBalancer
#   externalIPs:
#     - 192.168.49.104  # Fixed external IP
#   ports:
#     - protocol: TCP
#       port: 80          # Service port
#       targetPort: 80     # Container port
#       nodePort: 30632    # Fixed NodePort
apiVersion: v1
kind: Service
metadata:
  name: react-frontend
spec:
  selector:
    app: react-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer