apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: shebogimmy/back-finn:latest
        env:
        - name: DB_HOST
          value: "mysql" 
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: ""
        - name: DB_NAME
          value: "lms"
        ports:
        - containerPort: 3000