apiVersion: v1
kind: Service
metadata:
  name: node-backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
  type: LoadBalancer

# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-service
#   labels:
#     app: backend
# spec:
#   selector:
#     app: backend
#   ports:
#     - port: 80        
#       targetPort: 4000 
#       nodePort: 31693  
#   type: NodePort